### ISSUE TITLE
Sample Android APK file

### ISSUE THREAD

**Issue by Anwaarullah** [espressif/ESP8266_IOT_PLATFORM#1]
Team, I wasn't able to locate the sample Android template (.apk file). Can you please point me to it?
Thanks.

**Comment by jeremyloooo** [comment]
the sample APK file is published on https://github.com/EspressifApp/IOT- 
Espressif-Android， for more details you may load the 
30D_ESP_Smart_Plug__User_Guide__EN_v1.0_20150907.pdf in the 
esp8266_iot_platform github for reference.

Thanks.

在 2015/9/8 3:03, Syed Anwaarullah 写道:

**Comment by Anwaarullah** [comment]
Thanks @jeremyloooo. As indicated by you, found the Android example here: https://github.com/EspressifApp/IOT-Espressif-Android. Thanks.
